# Generated by Django 5.0.3 on 2024-05-13 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rwandan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_No', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^1\\d{15}$', message='Identity No. must be 16 digits starting with 1')])),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('father_names', models.CharField(max_length=200)),
                ('mother_names', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('non_active', 'Non-Active')], max_length=11)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
